name: Compile project on windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  QT_VERSION:         "6.3.2"
  MINGW_VERSION:      "11.2.0"
  MINGW_VERSION_ARCH: "win64_mingw"
  MINGW_PATH:         "mingw_64"
  BUILD_TYPE:         "Release"

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout project
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Install correct version of mingw
      uses: crazy-max/ghaction-chocolatey@v1
      with:
        args: install mingw --version=${{ env.MINGW_VERSION }} --force -y

    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        host: windows
        target: "desktop"
        version: ${{ env.QT_VERSION }}
        arch: ${{ env.MINGW_VERSION_ARCH }}
        dir: "${{github.workspace}}/qt"
        install-deps: "true"

    - name: Set Qt path and refresh
      run: |
        echo "${{github.workspace}}/qt/Qt/${{ env.QT_VERSION }}/${{ env.MINGW_PATH }}/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        refreshenv
        #Write-Output (Get-Command g++.exe).Path
        #g++.exe --version

    - name: Configure CMake Project
      working-directory: ${{github.workspace}}
      env:
        CMAKE_PREFIX_PATH: ${{env.Qt5_Dir}}
      run: cmake -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -G "CodeBlocks - MinGW Makefiles" -B ${{github.workspace}}/build

    - name: Build project
      working-directory: ${{github.workspace}}/build
      run: |
        mingw32-make.exe
